language: objective-c
osx_image: xcode7.2
env:
  global:
  - XCODE_PROJECT=Nemo.xcodeproj
  - XCODE_CONFIGURATION=Release
  - XCODE_SDK=iphonesimulator
  matrix:
  - XCODE_SCHEME=Nemo
  - XCODE_SCHEME=NemoExample
script:
- xctool -project $XCODE_PROJECT -scheme $XCODE_SCHEME -configuration $XCODE_CONFIGURATION -sdk $XCODE_SDK analyze
- pod lib lint
