name: Tests

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Xcode
      uses: sinoru/actions-setup-xcode@master
      with:
        xcode-version: 10.0
